$axure.loadCurrentPage({
  "url":"change.html",
  "generationDate":new Date(1387305292407.03),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d8ac82e3ea0a4e8ea38f8418f52afcd6",
    "type":"Axure:Page",
    "name":"change",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"bd74b0cf41c3455b96ff3fceb9b55a4a",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"cac9f17c63824a52a0523de90d338bf6"},
{
          "id":"9153919d75d2478c8db48355c4c144f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6699CC,
              "opacity":1},
            "location":{
              "x":640,
              "y":160},
            "size":{
              "width":320,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"407b5f95f2784f47b7352754f50aff5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6699CC,
                  "opacity":1},
                "location":{
                  "x":640,
                  "y":160},
                "size":{
                  "width":320,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u74.png"}},
{
          "id":"b8dcc530150e498792e4b9ec82c7acb9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":320,
              "y":100},
            "size":{
              "width":320,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b441a72c3192423392aa7d6168e8aa85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":320,
                  "y":100},
                "size":{
                  "width":320,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open humor in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"humor.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u76.png"}},
{
          "id":"593d80d3b4064a2582bce185ff4a7ff7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":640,
              "y":100},
            "size":{
              "width":320,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a2c8acf95804739941d02464436427f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":640,
                  "y":100},
                "size":{
                  "width":320,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open inspiration in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"inspiration.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u76.png"}},
{
          "id":"f506c1ec1bd54c3eb48e64ab358e5e72",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":0,
              "y":160},
            "size":{
              "width":320,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb37b396f27140a6aaea772fb6cf83f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":0,
                  "y":160},
                "size":{
                  "width":320,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open friendship in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"friendship.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u76.png"}},
{
          "id":"1defe4bbc4a64ce6b44c8f8ee5f1a15c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":320,
              "y":160},
            "size":{
              "width":320,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6f7c6fca03d4d168e916bda842411ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":320,
                  "y":160},
                "size":{
                  "width":320,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open love in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"love.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u76.png"}},
{
          "id":"934ce0b356304ce68068ca3a04582cdf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":0,
              "y":100},
            "size":{
              "width":320,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d90b4e87dce4927b13598e3fb654859",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":0,
                  "y":100},
                "size":{
                  "width":320,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u76.png"}},
{
          "id":"7a5d7d29831e4b0689857fd3fa1edd5c",
          "label":"quoteBox_cat6",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":220},
            "size":{
              "width":960,
              "height":400}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set quoteBox_cat6 to Next fade out 2000ms fade in 2000ms",
                      "panelsToStates":[{
                          "panelPath":["7a5d7d29831e4b0689857fd3fa1edd5c"],
                          "stateInfo":{
                            "setStateType":"next",
                            "stateNumber":0,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "animateOut":{
                                "easing":"fade",
                                "duration":2000},
                              "animateIn":{
                                "easing":"fade",
                                "duration":2000},
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"6bce9adeced346d4aef188e1886a3a61",
              "label":"quote1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"107b84d23a124d6ebea6a603ce7407d5",
                  "label":"",
                  "parentDynamicPanel":"7a5d7d29831e4b0689857fd3fa1edd5c",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"72px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":65,
                      "y":100},
                    "size":{
                      "width":35,
                      "height":83}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"881bb7e5df8049ccb3d11a5ef8647b19",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7a5d7d29831e4b0689857fd3fa1edd5c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"72px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":65,
                          "y":100},
                        "size":{
                          "width":35,
                          "height":83}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7a89e7ea6d9644bb95592b80aba1547e",
                  "label":"",
                  "parentDynamicPanel":"7a5d7d29831e4b0689857fd3fa1edd5c",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"72px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":860,
                      "y":100},
                    "size":{
                      "width":35,
                      "height":83}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c0e72f8207d547d984d9f0b73cf775db",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7a5d7d29831e4b0689857fd3fa1edd5c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"72px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":860,
                          "y":100},
                        "size":{
                          "width":35,
                          "height":83}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2d2cfcc7cb9f400989e602d96c122943",
                  "label":"",
                  "parentDynamicPanel":"7a5d7d29831e4b0689857fd3fa1edd5c",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"36px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF4F8AAE,
                      "opacity":1},
                    "location":{
                      "x":120,
                      "y":100},
                    "size":{
                      "width":720,
                      "height":42}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d0369e235618440d82f333af39466862",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7a5d7d29831e4b0689857fd3fa1edd5c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"36px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF4F8AAE,
                          "opacity":1},
                        "location":{
                          "x":120,
                          "y":100},
                        "size":{
                          "width":720,
                          "height":42}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"31bd3b655f444ed7ad52eb8262df1118",
                  "label":"",
                  "parentDynamicPanel":"7a5d7d29831e4b0689857fd3fa1edd5c",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":120,
                      "y":240},
                    "size":{
                      "width":720,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"34ab1b571d1243ed96e6d9bd6597a4c0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7a5d7d29831e4b0689857fd3fa1edd5c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":120,
                          "y":240},
                        "size":{
                          "width":720,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"53498b7dce0c4b1388c839e6d47b665e",
              "label":"quote2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"f6219feaeb3a4f9d8133b3c316a42426",
                  "label":"",
                  "parentDynamicPanel":"7a5d7d29831e4b0689857fd3fa1edd5c",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"72px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":65,
                      "y":100},
                    "size":{
                      "width":35,
                      "height":83}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3481d451d5484afb8020e6504182a0ef",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7a5d7d29831e4b0689857fd3fa1edd5c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"72px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":65,
                          "y":100},
                        "size":{
                          "width":35,
                          "height":83}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"090b08b2e0864280999c62376de58e25",
                  "label":"",
                  "parentDynamicPanel":"7a5d7d29831e4b0689857fd3fa1edd5c",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"72px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":860,
                      "y":100},
                    "size":{
                      "width":35,
                      "height":83}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"04d5568f30f4457fa4ca33451237a866",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7a5d7d29831e4b0689857fd3fa1edd5c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"72px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":860,
                          "y":100},
                        "size":{
                          "width":35,
                          "height":83}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"4d66c35d61c74242af6bd1b9fe115913",
                  "label":"",
                  "parentDynamicPanel":"7a5d7d29831e4b0689857fd3fa1edd5c",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"36px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF4F8AAE,
                      "opacity":1},
                    "location":{
                      "x":120,
                      "y":100},
                    "size":{
                      "width":720,
                      "height":84}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d87449202fce45e0a3d0088d30539a2d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7a5d7d29831e4b0689857fd3fa1edd5c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"36px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF4F8AAE,
                          "opacity":1},
                        "location":{
                          "x":120,
                          "y":100},
                        "size":{
                          "width":720,
                          "height":84}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"82ef11cd8a404d8ea1926f2c4f0c15ba",
                  "label":"",
                  "parentDynamicPanel":"7a5d7d29831e4b0689857fd3fa1edd5c",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":120,
                      "y":240},
                    "size":{
                      "width":720,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2767521cb7d44e58ae62bf6f6d942c0d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7a5d7d29831e4b0689857fd3fa1edd5c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":120,
                          "y":240},
                        "size":{
                          "width":720,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"d0d5c601b7d144cfb9c58816feb6cf10",
              "label":"quote3",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"b50fc65499d04303a82a4ea684c3ec07",
                  "label":"",
                  "parentDynamicPanel":"7a5d7d29831e4b0689857fd3fa1edd5c",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"72px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":65,
                      "y":100},
                    "size":{
                      "width":35,
                      "height":83}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6007b708a6934ebfbc29dd998eb4aa45",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7a5d7d29831e4b0689857fd3fa1edd5c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"72px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":65,
                          "y":100},
                        "size":{
                          "width":35,
                          "height":83}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8d38ae578d694555996e1a09ba352a6a",
                  "label":"",
                  "parentDynamicPanel":"7a5d7d29831e4b0689857fd3fa1edd5c",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"72px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":860,
                      "y":100},
                    "size":{
                      "width":35,
                      "height":83}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5784d9f2c29445ac8f0c6f6238d68a69",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7a5d7d29831e4b0689857fd3fa1edd5c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"72px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":860,
                          "y":100},
                        "size":{
                          "width":35,
                          "height":83}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"05abe2de8faf40f083da4bb42da1442e",
                  "label":"",
                  "parentDynamicPanel":"7a5d7d29831e4b0689857fd3fa1edd5c",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"36px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF4F8AAE,
                      "opacity":1},
                    "location":{
                      "x":120,
                      "y":100},
                    "size":{
                      "width":720,
                      "height":84}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"efc31fc5f19f4837a23c974b5f5b230a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7a5d7d29831e4b0689857fd3fa1edd5c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"36px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF4F8AAE,
                          "opacity":1},
                        "location":{
                          "x":120,
                          "y":100},
                        "size":{
                          "width":720,
                          "height":84}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"cfdb8785a2cd48288ff3985f5ac895b7",
                  "label":"",
                  "parentDynamicPanel":"7a5d7d29831e4b0689857fd3fa1edd5c",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":120,
                      "y":240},
                    "size":{
                      "width":720,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"829cf72af7984502a06496d8d4382ecb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7a5d7d29831e4b0689857fd3fa1edd5c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":120,
                          "y":240},
                        "size":{
                          "width":720,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"7ba2adc51e3440288defbd965836d0df",
              "label":"quote4",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"d595cb88bf9445b3aea391cac8257117",
                  "label":"",
                  "parentDynamicPanel":"7a5d7d29831e4b0689857fd3fa1edd5c",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"72px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":65,
                      "y":100},
                    "size":{
                      "width":35,
                      "height":83}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cbe738810a2346a58c1727d6c4d66fbf",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7a5d7d29831e4b0689857fd3fa1edd5c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"72px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":65,
                          "y":100},
                        "size":{
                          "width":35,
                          "height":83}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"eeadc89d0b324a1eaf50370d8fd88694",
                  "label":"",
                  "parentDynamicPanel":"7a5d7d29831e4b0689857fd3fa1edd5c",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"72px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":860,
                      "y":100},
                    "size":{
                      "width":35,
                      "height":83}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6a9fda2584484606a7359e4f975f890e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7a5d7d29831e4b0689857fd3fa1edd5c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"72px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":860,
                          "y":100},
                        "size":{
                          "width":35,
                          "height":83}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7f172bc164b84a9cbc4ef914525dfb19",
                  "label":"",
                  "parentDynamicPanel":"7a5d7d29831e4b0689857fd3fa1edd5c",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"36px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF4F8AAE,
                      "opacity":1},
                    "location":{
                      "x":120,
                      "y":100},
                    "size":{
                      "width":720,
                      "height":84}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7f507e8fa7fb478287b0e5d89fd4baf6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7a5d7d29831e4b0689857fd3fa1edd5c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"36px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF4F8AAE,
                          "opacity":1},
                        "location":{
                          "x":120,
                          "y":100},
                        "size":{
                          "width":720,
                          "height":84}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"bca197c4e9534ba19dfcbef7e73f67e8",
                  "label":"",
                  "parentDynamicPanel":"7a5d7d29831e4b0689857fd3fa1edd5c",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":120,
                      "y":240},
                    "size":{
                      "width":720,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b3dfa5885d9c4e7399a0e87681c52a43",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7a5d7d29831e4b0689857fd3fa1edd5c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":120,
                          "y":240},
                        "size":{
                          "width":720,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"14e1614d9dde43bbb660d93e55403afc",
              "label":"quote5",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"e12a8bf5c6ce4910b9a191a445917918",
                  "label":"",
                  "parentDynamicPanel":"7a5d7d29831e4b0689857fd3fa1edd5c",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"72px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":65,
                      "y":100},
                    "size":{
                      "width":35,
                      "height":83}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f7fddceb47de43fe92f70e2232d147f1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7a5d7d29831e4b0689857fd3fa1edd5c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"72px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":65,
                          "y":100},
                        "size":{
                          "width":35,
                          "height":83}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a6e69e45ff9545cfa53d14e6f9504617",
                  "label":"",
                  "parentDynamicPanel":"7a5d7d29831e4b0689857fd3fa1edd5c",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"72px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":860,
                      "y":100},
                    "size":{
                      "width":35,
                      "height":83}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c349fb322d33436a95290c7c80f70462",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7a5d7d29831e4b0689857fd3fa1edd5c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"72px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":860,
                          "y":100},
                        "size":{
                          "width":35,
                          "height":83}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e458cbef04d246f18ed2b6fd9630b38f",
                  "label":"",
                  "parentDynamicPanel":"7a5d7d29831e4b0689857fd3fa1edd5c",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"36px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF4F8AAE,
                      "opacity":1},
                    "location":{
                      "x":120,
                      "y":100},
                    "size":{
                      "width":720,
                      "height":84}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3f99f6d7a7b34fee8381aec99e14bb6b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7a5d7d29831e4b0689857fd3fa1edd5c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"36px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF4F8AAE,
                          "opacity":1},
                        "location":{
                          "x":120,
                          "y":100},
                        "size":{
                          "width":720,
                          "height":84}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0c3b93eb284a4a1a804c937bc9b8b71f",
                  "label":"",
                  "parentDynamicPanel":"7a5d7d29831e4b0689857fd3fa1edd5c",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":120,
                      "y":240},
                    "size":{
                      "width":720,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1696f0a2ffe34a90832d0031e18e3963",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7a5d7d29831e4b0689857fd3fa1edd5c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":120,
                          "y":240},
                        "size":{
                          "width":720,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]}]}},
  "masters":{
    "cac9f17c63824a52a0523de90d338bf6":{
      "packageId":"cac9f17c63824a52a0523de90d338bf6",
      "type":"Axure:Master",
      "name":"New Master 1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"1d0537ac680a48e0803fc441b8a70792",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":960,
                "height":640}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"59655ed6cfaf48ef851c9d9c5a34957f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":960,
                    "height":640}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u1.png"}},
{
            "id":"9398780670274a54b170f02388518565",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":960,
                "height":100}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"52d88341a3ef4370876955cba99f0d92",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":960,
                    "height":100}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u3.png"}},
{
            "id":"88f67b4b05a3469a8ee02fe251e1dd36",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":100,
                "height":100}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"aa35f9c188e94ca5ad65f6b9c81f4f26",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":100,
                    "height":100}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u5.png"}},
{
            "id":"50dfaf6678b24f6ab138899f4bbd6646",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "location":{
                "x":167,
                "y":293},
              "size":{
                "width":16,
                "height":37},
              "limbo":true},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"40ea58d891644651928d63a76a1eb044",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":167,
                    "y":293},
                  "size":{
                    "width":16,
                    "height":37},
                  "limbo":true},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"2e99d74433a745e98514195fd5ff9e55",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "location":{
                "x":177,
                "y":303},
              "size":{
                "width":16,
                "height":37},
              "limbo":true},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"72767b5952154ff79d927e7536f122d6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":177,
                    "y":303},
                  "size":{
                    "width":16,
                    "height":37},
                  "limbo":true},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"8c0b0319079844bb816732eb4d19bb70",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "location":{
                "x":294,
                "y":322},
              "size":{
                "width":137,
                "height":28},
              "limbo":true},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"43c245e859b84fddb3d04fb4f8800fcd",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":294,
                    "y":322},
                  "size":{
                    "width":137,
                    "height":28},
                  "limbo":true},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"025ba64a87434580a02052d8fa3f24b5",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":10},
              "size":{
                "width":200,
                "height":100},
              "limbo":true},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3353de2111b7414999f718eeafb2b732",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":10,
                    "y":10},
                  "size":{
                    "width":200,
                    "height":100},
                  "limbo":true},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u13.png"}},
{
            "id":"b0d3dd0d92e24655999695ee728e6630",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":10},
              "size":{
                "width":200,
                "height":100},
              "limbo":true},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"502304bffb104b539f281ced20e8eb74",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":10,
                    "y":10},
                  "size":{
                    "width":200,
                    "height":100},
                  "limbo":true},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u13.png"}},
{
            "id":"600ef7c96a9347bcb871100b36b0cf0f",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "location":{
                "x":127,
                "y":32},
              "size":{
                "width":144,
                "height":37},
              "limbo":true},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9dbfe63dbdc94bd8910e46f554fc4c00",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":127,
                    "y":32},
                  "size":{
                    "width":144,
                    "height":37},
                  "limbo":true},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"14e845e1c72e4821ace41b96db6ef19f",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":25,
                "y":25},
              "size":{
                "width":300,
                "height":300},
              "limbo":true},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e4bf41b15df04629ade763f9e50337ff",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":25,
                    "y":25},
                  "size":{
                    "width":300,
                    "height":300},
                  "limbo":true},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u19.jpg"}},
{
            "id":"a37335b01b9c4e39b9ddda5921a88092",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":10},
              "size":{
                "width":80,
                "height":80}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7b28f831d3ba40a4b373992dc4ec1da8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":10,
                    "y":10},
                  "size":{
                    "width":80,
                    "height":80}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u19.jpg"}},
{
            "id":"9f98275af8ba4d59ac90fb3f3575c6f2",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"48px",
              "location":{
                "x":120,
                "y":21.5},
              "size":{
                "width":213,
                "height":57}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2c21591a0d704951ba0f1be4b91877c2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"48px",
                  "location":{
                    "x":120,
                    "y":21.5},
                  "size":{
                    "width":213,
                    "height":57}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "bd74b0cf41c3455b96ff3fceb9b55a4a":{
      "scriptId":"u0",
      "1d0537ac680a48e0803fc441b8a70792":{
        "scriptId":"u1"},
      "59655ed6cfaf48ef851c9d9c5a34957f":{
        "scriptId":"u2"},
      "9398780670274a54b170f02388518565":{
        "scriptId":"u3"},
      "52d88341a3ef4370876955cba99f0d92":{
        "scriptId":"u4"},
      "88f67b4b05a3469a8ee02fe251e1dd36":{
        "scriptId":"u5"},
      "aa35f9c188e94ca5ad65f6b9c81f4f26":{
        "scriptId":"u6"},
      "50dfaf6678b24f6ab138899f4bbd6646":{
        "scriptId":"u7"},
      "40ea58d891644651928d63a76a1eb044":{
        "scriptId":"u8"},
      "2e99d74433a745e98514195fd5ff9e55":{
        "scriptId":"u9"},
      "72767b5952154ff79d927e7536f122d6":{
        "scriptId":"u10"},
      "8c0b0319079844bb816732eb4d19bb70":{
        "scriptId":"u11"},
      "43c245e859b84fddb3d04fb4f8800fcd":{
        "scriptId":"u12"},
      "025ba64a87434580a02052d8fa3f24b5":{
        "scriptId":"u13"},
      "3353de2111b7414999f718eeafb2b732":{
        "scriptId":"u14"},
      "b0d3dd0d92e24655999695ee728e6630":{
        "scriptId":"u15"},
      "502304bffb104b539f281ced20e8eb74":{
        "scriptId":"u16"},
      "600ef7c96a9347bcb871100b36b0cf0f":{
        "scriptId":"u17"},
      "9dbfe63dbdc94bd8910e46f554fc4c00":{
        "scriptId":"u18"},
      "14e845e1c72e4821ace41b96db6ef19f":{
        "scriptId":"u19"},
      "e4bf41b15df04629ade763f9e50337ff":{
        "scriptId":"u20"},
      "a37335b01b9c4e39b9ddda5921a88092":{
        "scriptId":"u21"},
      "7b28f831d3ba40a4b373992dc4ec1da8":{
        "scriptId":"u22"},
      "9f98275af8ba4d59ac90fb3f3575c6f2":{
        "scriptId":"u23"},
      "2c21591a0d704951ba0f1be4b91877c2":{
        "scriptId":"u24"}},
    "9153919d75d2478c8db48355c4c144f4":{
      "scriptId":"u25"},
    "407b5f95f2784f47b7352754f50aff5a":{
      "scriptId":"u26"},
    "b8dcc530150e498792e4b9ec82c7acb9":{
      "scriptId":"u27"},
    "b441a72c3192423392aa7d6168e8aa85":{
      "scriptId":"u28"},
    "593d80d3b4064a2582bce185ff4a7ff7":{
      "scriptId":"u29"},
    "0a2c8acf95804739941d02464436427f":{
      "scriptId":"u30"},
    "f506c1ec1bd54c3eb48e64ab358e5e72":{
      "scriptId":"u31"},
    "bb37b396f27140a6aaea772fb6cf83f3":{
      "scriptId":"u32"},
    "1defe4bbc4a64ce6b44c8f8ee5f1a15c":{
      "scriptId":"u33"},
    "a6f7c6fca03d4d168e916bda842411ab":{
      "scriptId":"u34"},
    "934ce0b356304ce68068ca3a04582cdf":{
      "scriptId":"u35"},
    "6d90b4e87dce4927b13598e3fb654859":{
      "scriptId":"u36"},
    "7a5d7d29831e4b0689857fd3fa1edd5c":{
      "scriptId":"u37"},
    "107b84d23a124d6ebea6a603ce7407d5":{
      "scriptId":"u38"},
    "881bb7e5df8049ccb3d11a5ef8647b19":{
      "scriptId":"u39"},
    "7a89e7ea6d9644bb95592b80aba1547e":{
      "scriptId":"u40"},
    "c0e72f8207d547d984d9f0b73cf775db":{
      "scriptId":"u41"},
    "2d2cfcc7cb9f400989e602d96c122943":{
      "scriptId":"u42"},
    "d0369e235618440d82f333af39466862":{
      "scriptId":"u43"},
    "31bd3b655f444ed7ad52eb8262df1118":{
      "scriptId":"u44"},
    "34ab1b571d1243ed96e6d9bd6597a4c0":{
      "scriptId":"u45"},
    "f6219feaeb3a4f9d8133b3c316a42426":{
      "scriptId":"u46"},
    "3481d451d5484afb8020e6504182a0ef":{
      "scriptId":"u47"},
    "090b08b2e0864280999c62376de58e25":{
      "scriptId":"u48"},
    "04d5568f30f4457fa4ca33451237a866":{
      "scriptId":"u49"},
    "4d66c35d61c74242af6bd1b9fe115913":{
      "scriptId":"u50"},
    "d87449202fce45e0a3d0088d30539a2d":{
      "scriptId":"u51"},
    "82ef11cd8a404d8ea1926f2c4f0c15ba":{
      "scriptId":"u52"},
    "2767521cb7d44e58ae62bf6f6d942c0d":{
      "scriptId":"u53"},
    "b50fc65499d04303a82a4ea684c3ec07":{
      "scriptId":"u54"},
    "6007b708a6934ebfbc29dd998eb4aa45":{
      "scriptId":"u55"},
    "8d38ae578d694555996e1a09ba352a6a":{
      "scriptId":"u56"},
    "5784d9f2c29445ac8f0c6f6238d68a69":{
      "scriptId":"u57"},
    "05abe2de8faf40f083da4bb42da1442e":{
      "scriptId":"u58"},
    "efc31fc5f19f4837a23c974b5f5b230a":{
      "scriptId":"u59"},
    "cfdb8785a2cd48288ff3985f5ac895b7":{
      "scriptId":"u60"},
    "829cf72af7984502a06496d8d4382ecb":{
      "scriptId":"u61"},
    "d595cb88bf9445b3aea391cac8257117":{
      "scriptId":"u62"},
    "cbe738810a2346a58c1727d6c4d66fbf":{
      "scriptId":"u63"},
    "eeadc89d0b324a1eaf50370d8fd88694":{
      "scriptId":"u64"},
    "6a9fda2584484606a7359e4f975f890e":{
      "scriptId":"u65"},
    "7f172bc164b84a9cbc4ef914525dfb19":{
      "scriptId":"u66"},
    "7f507e8fa7fb478287b0e5d89fd4baf6":{
      "scriptId":"u67"},
    "bca197c4e9534ba19dfcbef7e73f67e8":{
      "scriptId":"u68"},
    "b3dfa5885d9c4e7399a0e87681c52a43":{
      "scriptId":"u69"},
    "e12a8bf5c6ce4910b9a191a445917918":{
      "scriptId":"u70"},
    "f7fddceb47de43fe92f70e2232d147f1":{
      "scriptId":"u71"},
    "a6e69e45ff9545cfa53d14e6f9504617":{
      "scriptId":"u72"},
    "c349fb322d33436a95290c7c80f70462":{
      "scriptId":"u73"},
    "e458cbef04d246f18ed2b6fd9630b38f":{
      "scriptId":"u74"},
    "3f99f6d7a7b34fee8381aec99e14bb6b":{
      "scriptId":"u75"},
    "0c3b93eb284a4a1a804c937bc9b8b71f":{
      "scriptId":"u76"},
    "1696f0a2ffe34a90832d0031e18e3963":{
      "scriptId":"u77"}}});