$axure.loadCurrentPage({
  "url":"yourquoteslist.html",
  "generationDate":new Date(1387489002372.37),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ed9160d9dcb141048833329d93ca76ae",
    "type":"Axure:Page",
    "name":"yourQuotesList",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
      "a":{
},
      "b":{
},
      "c":{
},
      "d":{
}},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e55fdac534fa4d7cb52c065385df42b0",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
            "a":{
},
            "b":{
},
            "c":{
},
            "d":{
}},
          "masterId":"74dd9fa4ef174a4aac68bd408b906866"},
{
          "id":"a25c6ff066ee4655b032e620d658bbd9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":250},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
            "a":{
},
            "b":{
},
            "c":{
},
            "d":{
}},
          "objects":[{
              "id":"f54f5916551c4fc78541294b3fb3320c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":250},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
                "a":{
},
                "b":{
},
                "c":{
},
                "d":{
}}}],
          "images":{
            "normal~":"images/yourquoteslist/u27.png"}}]}},
  "masters":{
    "74dd9fa4ef174a4aac68bd408b906866":{
      "packageId":"74dd9fa4ef174a4aac68bd408b906866",
      "type":"Axure:Master",
      "name":"Page layout",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
        "a":{
},
        "b":{
},
        "c":{
},
        "d":{
}},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"766a3c30dfc24a7783792582c6706a40",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "size":{
                "width":320,
                "height":480},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
              "a":{
},
              "b":{
                "size":{
                  "width":480,
                  "height":50}},
              "c":{
},
              "d":{
}},
            "objects":[{
                "id":"73f9110a837f4323b57cb901065f9905",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "size":{
                    "width":320,
                    "height":480},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
                  "a":{
},
                  "b":{
},
                  "c":{
},
                  "d":{
}}}],
            "images":{
              "normal~":"images/home/u1.png",
              "normal~b":"images/home/u1_b.png",
              "normal~c":"images/home/u1_b.png",
              "normal~d":"images/home/u1_b.png"}},
{
            "id":"70f43fbfbf584b84a57af9421ea4ce01",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":320,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
              "a":{
},
              "b":{
                "size":{
                  "width":480,
                  "height":50}},
              "c":{
},
              "d":{
}},
            "objects":[{
                "id":"9f833909bd2d486da91c8451f84e7a28",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":320,
                    "height":50},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
                  "a":{
},
                  "b":{
},
                  "c":{
},
                  "d":{
}}}],
            "images":{
              "normal~":"images/home/u3.png",
              "normal~b":"images/home/u3_b.png",
              "normal~c":"images/home/u3_b.png",
              "normal~d":"images/home/u3_b.png"}},
{
            "id":"ee674a5562fc4aba8a5e2330fad40f13",
            "label":"",
            "type":"referenceDiagramObject",
            "styleType":"referenceDiagramObject",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":409}},
            "adaptiveStyles":{
              "a":{
},
              "b":{
},
              "c":{
},
              "d":{
}},
            "masterId":"81e3124032df45c4b52c40520e5abd12"}]}},
    "81e3124032df45c4b52c40520e5abd12":{
      "packageId":"81e3124032df45c4b52c40520e5abd12",
      "type":"Axure:Master",
      "name":"Footer",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
        "a":{
},
        "b":{
},
        "c":{
},
        "d":{
}},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"b7da9bb0976a4d09a514079ff3c6acff",
            "label":"",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "size":{
                "width":10,
                "height":10}},
            "adaptiveStyles":{
              "a":{
},
              "b":{
},
              "c":{
},
              "d":{
}},
            "fixedHorizontal":"left",
            "fixedMarginHorizontal":0,
            "fixedVertical":"bottom",
            "fixedMarginVertical":0,
            "fixedKeepInFront":true,
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"6fd60091b1b048b09da79479ad24a70e",
                "label":"home",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"bf84f4d025c3484eba56b59e326ca49a",
                    "label":"",
                    "parentDynamicPanel":"b7da9bb0976a4d09a514079ff3c6acff",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":7},
                      "size":{
                        "width":320,
                        "height":64}},
                    "adaptiveStyles":{
                      "a":{
},
                      "b":{
},
                      "c":{
},
                      "d":{
}},
                    "objects":[{
                        "id":"b6c22247f71043169fa406d58dfaa95c",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"b7da9bb0976a4d09a514079ff3c6acff",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":0,
                            "y":7},
                          "size":{
                            "width":320,
                            "height":64}},
                        "adaptiveStyles":{
                          "a":{
},
                          "b":{
},
                          "c":{
},
                          "d":{
}}}],
                    "images":{
                      "normal~":"images/home/u7.png"}},
{
                    "id":"a7e76f452f394ea38f3ea02baa2535e9",
                    "label":"",
                    "parentDynamicPanel":"b7da9bb0976a4d09a514079ff3c6acff",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontSize":"11px",
                      "verticalAlignment":"bottom",
                      "paddingBottom":"8",
                      "location":{
                        "x":0,
                        "y":7},
                      "size":{
                        "width":64,
                        "height":64}},
                    "adaptiveStyles":{
                      "a":{
},
                      "b":{
},
                      "c":{
},
                      "d":{
}},
                    "objects":[{
                        "id":"44d3b17765d94488bf566dc947924eb9",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"b7da9bb0976a4d09a514079ff3c6acff",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"11px",
                          "verticalAlignment":"bottom",
                          "paddingBottom":"8",
                          "location":{
                            "x":0,
                            "y":7},
                          "size":{
                            "width":64,
                            "height":64}},
                        "adaptiveStyles":{
                          "a":{
},
                          "b":{
},
                          "c":{
},
                          "d":{
}}}],
                    "images":{
                      "normal~":"images/home/u9.png"}},
{
                    "id":"03094a20195044689d35c7538d3f4fb3",
                    "label":"",
                    "parentDynamicPanel":"b7da9bb0976a4d09a514079ff3c6acff",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontSize":"11px",
                      "verticalAlignment":"bottom",
                      "paddingBottom":"8",
                      "location":{
                        "x":192,
                        "y":7},
                      "size":{
                        "width":64,
                        "height":64}},
                    "adaptiveStyles":{
                      "a":{
},
                      "b":{
},
                      "c":{
},
                      "d":{
}},
                    "objects":[{
                        "id":"6af711dae81a4505987b39a68f394636",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"b7da9bb0976a4d09a514079ff3c6acff",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"11px",
                          "verticalAlignment":"bottom",
                          "paddingBottom":"8",
                          "location":{
                            "x":192,
                            "y":7},
                          "size":{
                            "width":64,
                            "height":64}},
                        "adaptiveStyles":{
                          "a":{
},
                          "b":{
},
                          "c":{
},
                          "d":{
}}}],
                    "images":{
                      "normal~":"images/home/u9.png"}},
{
                    "id":"f8d897a61e5740369871ee34108937d5",
                    "label":"",
                    "parentDynamicPanel":"b7da9bb0976a4d09a514079ff3c6acff",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontSize":"11px",
                      "verticalAlignment":"bottom",
                      "paddingBottom":"8",
                      "location":{
                        "x":256,
                        "y":7},
                      "size":{
                        "width":64,
                        "height":64}},
                    "adaptiveStyles":{
                      "a":{
},
                      "b":{
},
                      "c":{
},
                      "d":{
}},
                    "objects":[{
                        "id":"e1db7a57c91a40d4a534c3c74dacb1e8",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"b7da9bb0976a4d09a514079ff3c6acff",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"11px",
                          "verticalAlignment":"bottom",
                          "paddingBottom":"8",
                          "location":{
                            "x":256,
                            "y":7},
                          "size":{
                            "width":64,
                            "height":64}},
                        "adaptiveStyles":{
                          "a":{
},
                          "b":{
},
                          "c":{
},
                          "d":{
}}}],
                    "images":{
                      "normal~":"images/home/u9.png"}},
{
                    "id":"13192bb9cc114c65a8949abdcbb947b2",
                    "label":"",
                    "parentDynamicPanel":"b7da9bb0976a4d09a514079ff3c6acff",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontSize":"11px",
                      "verticalAlignment":"bottom",
                      "paddingBottom":"8",
                      "location":{
                        "x":64,
                        "y":7},
                      "size":{
                        "width":64,
                        "height":64}},
                    "adaptiveStyles":{
                      "a":{
},
                      "b":{
},
                      "c":{
},
                      "d":{
}},
                    "objects":[{
                        "id":"416c2efe574f45d08f25da1c59353f07",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"b7da9bb0976a4d09a514079ff3c6acff",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"11px",
                          "verticalAlignment":"bottom",
                          "paddingBottom":"8",
                          "location":{
                            "x":64,
                            "y":7},
                          "size":{
                            "width":64,
                            "height":64}},
                        "adaptiveStyles":{
                          "a":{
},
                          "b":{
},
                          "c":{
},
                          "d":{
}}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open yourQuotes in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"yourquotes.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/home/u9.png"}},
{
                    "id":"3d33648afbd94ced97df13ea358e3e44",
                    "label":"",
                    "parentDynamicPanel":"b7da9bb0976a4d09a514079ff3c6acff",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":125,
                        "y":0},
                      "size":{
                        "width":70,
                        "height":70}},
                    "adaptiveStyles":{
                      "a":{
},
                      "b":{
},
                      "c":{
},
                      "d":{
}},
                    "objects":[{
                        "id":"b4c1771e93a64c58b80c76798f4b5ae9",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"b7da9bb0976a4d09a514079ff3c6acff",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":125,
                            "y":0},
                          "size":{
                            "width":70,
                            "height":70}},
                        "adaptiveStyles":{
                          "a":{
},
                          "b":{
},
                          "c":{
},
                          "d":{
}}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Home in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"home.html",
                                  "includeVariables":true},
                                "linkType":"current"},
{
                                "action":"setPanelState",
                                "description":"Set Panel to State",
                                "panelsToStates":[]}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/home/u17.png"}},
{
                    "id":"9f2fad9a5e494d35b769bd7ae4796e78",
                    "label":"",
                    "parentDynamicPanel":"b7da9bb0976a4d09a514079ff3c6acff",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":276,
                        "y":20},
                      "size":{
                        "width":24,
                        "height":24}},
                    "adaptiveStyles":{
                      "a":{
},
                      "b":{
},
                      "c":{
},
                      "d":{
}},
                    "objects":[{
                        "id":"448186e4a6e8449081e5a9caf0aa5cf9",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"b7da9bb0976a4d09a514079ff3c6acff",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":276,
                            "y":20},
                          "size":{
                            "width":24,
                            "height":24}},
                        "adaptiveStyles":{
                          "a":{
},
                          "b":{
},
                          "c":{
},
                          "d":{
}}}],
                    "images":{
                      "normal~":"images/home/u19.png"}},
{
                    "id":"8ef36dee43844e549539bf19321f6751",
                    "label":"",
                    "parentDynamicPanel":"b7da9bb0976a4d09a514079ff3c6acff",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":212,
                        "y":20},
                      "size":{
                        "width":24,
                        "height":24}},
                    "adaptiveStyles":{
                      "a":{
},
                      "b":{
},
                      "c":{
},
                      "d":{
}},
                    "objects":[{
                        "id":"c2b207dfdce64aa2a820c62bbfc8594c",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"b7da9bb0976a4d09a514079ff3c6acff",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":212,
                            "y":20},
                          "size":{
                            "width":24,
                            "height":24}},
                        "adaptiveStyles":{
                          "a":{
},
                          "b":{
},
                          "c":{
},
                          "d":{
}}}],
                    "images":{
                      "normal~":"images/home/u21.png"}},
{
                    "id":"c80bcda215c54bae8273e0c29c3a5672",
                    "label":"",
                    "parentDynamicPanel":"b7da9bb0976a4d09a514079ff3c6acff",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":20,
                        "y":20},
                      "size":{
                        "width":24,
                        "height":24}},
                    "adaptiveStyles":{
                      "a":{
},
                      "b":{
},
                      "c":{
},
                      "d":{
}},
                    "objects":[{
                        "id":"16bed04558de43929f2796d72a5e92f8",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"b7da9bb0976a4d09a514079ff3c6acff",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":20,
                            "y":20},
                          "size":{
                            "width":24,
                            "height":24}},
                        "adaptiveStyles":{
                          "a":{
},
                          "b":{
},
                          "c":{
},
                          "d":{
}}}],
                    "images":{
                      "normal~":"images/home/u23.png"}},
{
                    "id":"07b81fac2002495e90163c9f8d90a704",
                    "label":"",
                    "parentDynamicPanel":"b7da9bb0976a4d09a514079ff3c6acff",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":84,
                        "y":20},
                      "size":{
                        "width":24,
                        "height":24}},
                    "adaptiveStyles":{
                      "a":{
},
                      "b":{
},
                      "c":{
},
                      "d":{
}},
                    "objects":[{
                        "id":"d9f80184908348ac92275bf83847dcc2",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"b7da9bb0976a4d09a514079ff3c6acff",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":84,
                            "y":20},
                          "size":{
                            "width":24,
                            "height":24}},
                        "adaptiveStyles":{
                          "a":{
},
                          "b":{
},
                          "c":{
},
                          "d":{
}}}],
                    "images":{
                      "normal~":"images/home/u25.png"}}]},
{
                "id":"d0da18bd03ab4335a7f2870bb12eea4b",
                "label":"create",
                "type":"Axure:PanelDiagram",
                "objects":[]},
{
                "id":"54223a311e8b43b9afb352f62c0edfcc",
                "label":"yourQ",
                "type":"Axure:PanelDiagram",
                "objects":[]},
{
                "id":"bc049b957776425490a73ddc1a5ecb2e",
                "label":"find",
                "type":"Axure:PanelDiagram",
                "objects":[]},
{
                "id":"a387d562838b4f2590f2d24112b54d43",
                "label":"settings",
                "type":"Axure:PanelDiagram",
                "objects":[]}]}]}}},
  "objectPaths":{
    "e55fdac534fa4d7cb52c065385df42b0":{
      "scriptId":"u0",
      "766a3c30dfc24a7783792582c6706a40":{
        "scriptId":"u1"},
      "73f9110a837f4323b57cb901065f9905":{
        "scriptId":"u2"},
      "70f43fbfbf584b84a57af9421ea4ce01":{
        "scriptId":"u3"},
      "9f833909bd2d486da91c8451f84e7a28":{
        "scriptId":"u4"},
      "ee674a5562fc4aba8a5e2330fad40f13":{
        "scriptId":"u5",
        "b7da9bb0976a4d09a514079ff3c6acff":{
          "scriptId":"u6"},
        "bf84f4d025c3484eba56b59e326ca49a":{
          "scriptId":"u7"},
        "b6c22247f71043169fa406d58dfaa95c":{
          "scriptId":"u8"},
        "a7e76f452f394ea38f3ea02baa2535e9":{
          "scriptId":"u9"},
        "44d3b17765d94488bf566dc947924eb9":{
          "scriptId":"u10"},
        "03094a20195044689d35c7538d3f4fb3":{
          "scriptId":"u11"},
        "6af711dae81a4505987b39a68f394636":{
          "scriptId":"u12"},
        "f8d897a61e5740369871ee34108937d5":{
          "scriptId":"u13"},
        "e1db7a57c91a40d4a534c3c74dacb1e8":{
          "scriptId":"u14"},
        "13192bb9cc114c65a8949abdcbb947b2":{
          "scriptId":"u15"},
        "416c2efe574f45d08f25da1c59353f07":{
          "scriptId":"u16"},
        "3d33648afbd94ced97df13ea358e3e44":{
          "scriptId":"u17"},
        "b4c1771e93a64c58b80c76798f4b5ae9":{
          "scriptId":"u18"},
        "9f2fad9a5e494d35b769bd7ae4796e78":{
          "scriptId":"u19"},
        "448186e4a6e8449081e5a9caf0aa5cf9":{
          "scriptId":"u20"},
        "8ef36dee43844e549539bf19321f6751":{
          "scriptId":"u21"},
        "c2b207dfdce64aa2a820c62bbfc8594c":{
          "scriptId":"u22"},
        "c80bcda215c54bae8273e0c29c3a5672":{
          "scriptId":"u23"},
        "16bed04558de43929f2796d72a5e92f8":{
          "scriptId":"u24"},
        "07b81fac2002495e90163c9f8d90a704":{
          "scriptId":"u25"},
        "d9f80184908348ac92275bf83847dcc2":{
          "scriptId":"u26"}}},
    "a25c6ff066ee4655b032e620d658bbd9":{
      "scriptId":"u27"},
    "f54f5916551c4fc78541294b3fb3320c":{
      "scriptId":"u28"}}});