$axure.loadCurrentPage({
  "url":"love.html",
  "generationDate":new Date(1387305292216.02),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b9e2b7ae85d24752a766ae9671e0512a",
    "type":"Axure:Page",
    "name":"love",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5b0694fa5f124324891293724a098df2",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"cac9f17c63824a52a0523de90d338bf6"},
{
          "id":"b9f3f8db01cc41c3937d658debf8826a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6699CC,
              "opacity":1},
            "location":{
              "x":320,
              "y":160},
            "size":{
              "width":320,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa0590c4566044ad9a32b26cf627a6a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6699CC,
                  "opacity":1},
                "location":{
                  "x":320,
                  "y":160},
                "size":{
                  "width":320,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u74.png"}},
{
          "id":"eca95f228c7e49d88531357fde172a1b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":320,
              "y":100},
            "size":{
              "width":320,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a8e434e2cdb4135aeb402b19892510a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":320,
                  "y":100},
                "size":{
                  "width":320,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open humor in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"humor.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u76.png"}},
{
          "id":"2ec6a4d4562c4f2f9a088544a1cc8576",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":640,
              "y":100},
            "size":{
              "width":320,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b89375047bed4b7cb97aa5a42c78e5bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":640,
                  "y":100},
                "size":{
                  "width":320,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open inspiration in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"inspiration.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u76.png"}},
{
          "id":"b459c807b1b34fb98ad800819447ad12",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":0,
              "y":160},
            "size":{
              "width":320,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9fa2af8ef46a4fcc885e6d063179ed6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":0,
                  "y":160},
                "size":{
                  "width":320,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open friendship in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"friendship.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u76.png"}},
{
          "id":"d725abd2247f465dbf598cde35c26b2c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":640,
              "y":160},
            "size":{
              "width":320,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e6e7b840daa41fdb7827b3a82764b9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":640,
                  "y":160},
                "size":{
                  "width":320,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open change in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"change.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u76.png"}},
{
          "id":"e8eee0a4e47a47d988623060b9f709b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":0,
              "y":100},
            "size":{
              "width":320,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa99630c5a404a9dbe1c34e2a375eda9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":0,
                  "y":100},
                "size":{
                  "width":320,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u76.png"}},
{
          "id":"2e8ea0374dda46889ecad7ce0d8ec4c8",
          "label":"quoteBox_cat5",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":220},
            "size":{
              "width":960,
              "height":400}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set quoteBox_cat5 to Next fade out 2000ms fade in 2000ms",
                      "panelsToStates":[{
                          "panelPath":["2e8ea0374dda46889ecad7ce0d8ec4c8"],
                          "stateInfo":{
                            "setStateType":"next",
                            "stateNumber":0,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "animateOut":{
                                "easing":"fade",
                                "duration":2000},
                              "animateIn":{
                                "easing":"fade",
                                "duration":2000},
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"fcf7fac28fae4e24b96954f12294af20",
              "label":"theresa",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"db137071e37b46a4b23c791d9953a02e",
                  "label":"",
                  "parentDynamicPanel":"2e8ea0374dda46889ecad7ce0d8ec4c8",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"72px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":65,
                      "y":100},
                    "size":{
                      "width":35,
                      "height":83}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"49d0b1d6b6224a88991e6d19c5d8bbf3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2e8ea0374dda46889ecad7ce0d8ec4c8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"72px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":65,
                          "y":100},
                        "size":{
                          "width":35,
                          "height":83}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"46ac675f507e4e3db6b57a2f785d17d9",
                  "label":"",
                  "parentDynamicPanel":"2e8ea0374dda46889ecad7ce0d8ec4c8",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"72px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":860,
                      "y":100},
                    "size":{
                      "width":35,
                      "height":83}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4669108ea7654f4c954c5f1662f5ad27",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2e8ea0374dda46889ecad7ce0d8ec4c8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"72px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":860,
                          "y":100},
                        "size":{
                          "width":35,
                          "height":83}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"12b37dac75ff4679a3e29cc3ab97b2e5",
                  "label":"",
                  "parentDynamicPanel":"2e8ea0374dda46889ecad7ce0d8ec4c8",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"36px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF4F8AAE,
                      "opacity":1},
                    "location":{
                      "x":120,
                      "y":100},
                    "size":{
                      "width":720,
                      "height":126}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2caf079f992048228699aef3b4344598",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2e8ea0374dda46889ecad7ce0d8ec4c8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"36px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF4F8AAE,
                          "opacity":1},
                        "location":{
                          "x":120,
                          "y":100},
                        "size":{
                          "width":720,
                          "height":126}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"84a796e01c45429ca8c41a00fa5e7df0",
                  "label":"",
                  "parentDynamicPanel":"2e8ea0374dda46889ecad7ce0d8ec4c8",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":120,
                      "y":240},
                    "size":{
                      "width":720,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b0d5e97de0444420898f938bcb63f8a3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2e8ea0374dda46889ecad7ce0d8ec4c8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":120,
                          "y":240},
                        "size":{
                          "width":720,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"55b711b3778d4f9cbaf551f4a2c5d6b5",
              "label":"woody",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"6df2c976c7514e89995070f7cfedd7bf",
                  "label":"",
                  "parentDynamicPanel":"2e8ea0374dda46889ecad7ce0d8ec4c8",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"72px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":65,
                      "y":100},
                    "size":{
                      "width":35,
                      "height":83}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e98d3ff7e862439cbf5a0fa48961e499",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2e8ea0374dda46889ecad7ce0d8ec4c8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"72px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":65,
                          "y":100},
                        "size":{
                          "width":35,
                          "height":83}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3c878be9d1524c51a6412ffd54030d2d",
                  "label":"",
                  "parentDynamicPanel":"2e8ea0374dda46889ecad7ce0d8ec4c8",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"72px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":860,
                      "y":100},
                    "size":{
                      "width":35,
                      "height":83}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"eb17fe640fc3439592685928f14fc4df",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2e8ea0374dda46889ecad7ce0d8ec4c8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"72px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":860,
                          "y":100},
                        "size":{
                          "width":35,
                          "height":83}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"762605ca52744105b4b979b0b2e143bc",
                  "label":"",
                  "parentDynamicPanel":"2e8ea0374dda46889ecad7ce0d8ec4c8",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"36px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF4F8AAE,
                      "opacity":1},
                    "location":{
                      "x":120,
                      "y":100},
                    "size":{
                      "width":720,
                      "height":84}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2f2ed094f9d74b048f72f07d7b9c0176",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2e8ea0374dda46889ecad7ce0d8ec4c8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"36px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF4F8AAE,
                          "opacity":1},
                        "location":{
                          "x":120,
                          "y":100},
                        "size":{
                          "width":720,
                          "height":84}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"286f50c9844f4312a54e31c962297408",
                  "label":"",
                  "parentDynamicPanel":"2e8ea0374dda46889ecad7ce0d8ec4c8",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":120,
                      "y":240},
                    "size":{
                      "width":720,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0f914af27aec40b8b1d4ca136f666968",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2e8ea0374dda46889ecad7ce0d8ec4c8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":120,
                          "y":240},
                        "size":{
                          "width":720,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"4c82d73c2fc64efe975d8207ce46223d",
              "label":"fromm",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"ed7940385b88436ab99b4b920a04ebbc",
                  "label":"",
                  "parentDynamicPanel":"2e8ea0374dda46889ecad7ce0d8ec4c8",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"72px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":65,
                      "y":100},
                    "size":{
                      "width":35,
                      "height":83}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d79bbc7992324f3fbdc84c290dcefbf3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2e8ea0374dda46889ecad7ce0d8ec4c8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"72px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":65,
                          "y":100},
                        "size":{
                          "width":35,
                          "height":83}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e7b5bcecd6ae440e8dd5b30dd482162c",
                  "label":"",
                  "parentDynamicPanel":"2e8ea0374dda46889ecad7ce0d8ec4c8",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"72px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":860,
                      "y":100},
                    "size":{
                      "width":35,
                      "height":83}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a731598b326e4754904474525494bf5d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2e8ea0374dda46889ecad7ce0d8ec4c8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"72px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":860,
                          "y":100},
                        "size":{
                          "width":35,
                          "height":83}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1d72b63d028c4cb29785ae1b1b5c8488",
                  "label":"",
                  "parentDynamicPanel":"2e8ea0374dda46889ecad7ce0d8ec4c8",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"36px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF4F8AAE,
                      "opacity":1},
                    "location":{
                      "x":120,
                      "y":100},
                    "size":{
                      "width":720,
                      "height":126}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"da6b56554d0341e5ac6afcf1f23ec29e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2e8ea0374dda46889ecad7ce0d8ec4c8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"36px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF4F8AAE,
                          "opacity":1},
                        "location":{
                          "x":120,
                          "y":100},
                        "size":{
                          "width":720,
                          "height":126}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f46b6fdcb45e4729bf50ae8c084d2013",
                  "label":"",
                  "parentDynamicPanel":"2e8ea0374dda46889ecad7ce0d8ec4c8",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":120,
                      "y":240},
                    "size":{
                      "width":720,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5532b2435dbf4dc5beb9413223b3c3a8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2e8ea0374dda46889ecad7ce0d8ec4c8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":120,
                          "y":240},
                        "size":{
                          "width":720,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"7f3b4b8dc77546fa9212717cf84c11a4",
              "label":"quote4",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"26ae6a92f02c4c5898541732034d99f7",
                  "label":"",
                  "parentDynamicPanel":"2e8ea0374dda46889ecad7ce0d8ec4c8",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"72px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":65,
                      "y":100},
                    "size":{
                      "width":35,
                      "height":83}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"33022466b334494bbe496a1f6abc4454",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2e8ea0374dda46889ecad7ce0d8ec4c8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"72px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":65,
                          "y":100},
                        "size":{
                          "width":35,
                          "height":83}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e6243989932744e9b52888724a976259",
                  "label":"",
                  "parentDynamicPanel":"2e8ea0374dda46889ecad7ce0d8ec4c8",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"72px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":860,
                      "y":100},
                    "size":{
                      "width":35,
                      "height":83}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8d860daa821042d3b60308b5304a80cc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2e8ea0374dda46889ecad7ce0d8ec4c8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"72px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":860,
                          "y":100},
                        "size":{
                          "width":35,
                          "height":83}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d725e0e8310041b0b07a89db9773793e",
                  "label":"",
                  "parentDynamicPanel":"2e8ea0374dda46889ecad7ce0d8ec4c8",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"36px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF4F8AAE,
                      "opacity":1},
                    "location":{
                      "x":120,
                      "y":100},
                    "size":{
                      "width":720,
                      "height":84}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"995af751f1e24acf95fc3fec975af5ad",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2e8ea0374dda46889ecad7ce0d8ec4c8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"36px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF4F8AAE,
                          "opacity":1},
                        "location":{
                          "x":120,
                          "y":100},
                        "size":{
                          "width":720,
                          "height":84}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"aedbe898a9914a88a71b74f39404a028",
                  "label":"",
                  "parentDynamicPanel":"2e8ea0374dda46889ecad7ce0d8ec4c8",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":120,
                      "y":240},
                    "size":{
                      "width":720,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"faac3fca3004411189b14e2c44733fa4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2e8ea0374dda46889ecad7ce0d8ec4c8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":120,
                          "y":240},
                        "size":{
                          "width":720,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"e0a82a5eeeef461fbb05943fd954a089",
              "label":"quote5",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"b71dc9e1c8d247fea9c1897c350895cd",
                  "label":"",
                  "parentDynamicPanel":"2e8ea0374dda46889ecad7ce0d8ec4c8",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"72px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":65,
                      "y":100},
                    "size":{
                      "width":35,
                      "height":83}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0904024649524f1fb88509f390b96fc2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2e8ea0374dda46889ecad7ce0d8ec4c8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"72px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":65,
                          "y":100},
                        "size":{
                          "width":35,
                          "height":83}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"439349667d2942efb01816260ddbb79d",
                  "label":"",
                  "parentDynamicPanel":"2e8ea0374dda46889ecad7ce0d8ec4c8",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"72px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":860,
                      "y":100},
                    "size":{
                      "width":35,
                      "height":83}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5e9df077bc0445d0a614423156aca41b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2e8ea0374dda46889ecad7ce0d8ec4c8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"72px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":860,
                          "y":100},
                        "size":{
                          "width":35,
                          "height":83}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c845e20136b9420fb842933f9e833b62",
                  "label":"",
                  "parentDynamicPanel":"2e8ea0374dda46889ecad7ce0d8ec4c8",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"36px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF4F8AAE,
                      "opacity":1},
                    "location":{
                      "x":120,
                      "y":100},
                    "size":{
                      "width":720,
                      "height":84}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b3faffba4013445c9a42fe5ddb353fd0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2e8ea0374dda46889ecad7ce0d8ec4c8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"36px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF4F8AAE,
                          "opacity":1},
                        "location":{
                          "x":120,
                          "y":100},
                        "size":{
                          "width":720,
                          "height":84}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8038735d15b943788414ed1ed01a1720",
                  "label":"",
                  "parentDynamicPanel":"2e8ea0374dda46889ecad7ce0d8ec4c8",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":120,
                      "y":240},
                    "size":{
                      "width":720,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1db85302cc014a9c9b33915530577a44",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2e8ea0374dda46889ecad7ce0d8ec4c8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":120,
                          "y":240},
                        "size":{
                          "width":720,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]}]}},
  "masters":{
    "cac9f17c63824a52a0523de90d338bf6":{
      "packageId":"cac9f17c63824a52a0523de90d338bf6",
      "type":"Axure:Master",
      "name":"New Master 1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"1d0537ac680a48e0803fc441b8a70792",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":960,
                "height":640}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"59655ed6cfaf48ef851c9d9c5a34957f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":960,
                    "height":640}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u1.png"}},
{
            "id":"9398780670274a54b170f02388518565",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":960,
                "height":100}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"52d88341a3ef4370876955cba99f0d92",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":960,
                    "height":100}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u3.png"}},
{
            "id":"88f67b4b05a3469a8ee02fe251e1dd36",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":100,
                "height":100}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"aa35f9c188e94ca5ad65f6b9c81f4f26",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":100,
                    "height":100}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u5.png"}},
{
            "id":"50dfaf6678b24f6ab138899f4bbd6646",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "location":{
                "x":167,
                "y":293},
              "size":{
                "width":16,
                "height":37},
              "limbo":true},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"40ea58d891644651928d63a76a1eb044",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":167,
                    "y":293},
                  "size":{
                    "width":16,
                    "height":37},
                  "limbo":true},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"2e99d74433a745e98514195fd5ff9e55",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "location":{
                "x":177,
                "y":303},
              "size":{
                "width":16,
                "height":37},
              "limbo":true},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"72767b5952154ff79d927e7536f122d6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":177,
                    "y":303},
                  "size":{
                    "width":16,
                    "height":37},
                  "limbo":true},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"8c0b0319079844bb816732eb4d19bb70",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "location":{
                "x":294,
                "y":322},
              "size":{
                "width":137,
                "height":28},
              "limbo":true},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"43c245e859b84fddb3d04fb4f8800fcd",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":294,
                    "y":322},
                  "size":{
                    "width":137,
                    "height":28},
                  "limbo":true},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"025ba64a87434580a02052d8fa3f24b5",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":10},
              "size":{
                "width":200,
                "height":100},
              "limbo":true},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3353de2111b7414999f718eeafb2b732",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":10,
                    "y":10},
                  "size":{
                    "width":200,
                    "height":100},
                  "limbo":true},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u13.png"}},
{
            "id":"b0d3dd0d92e24655999695ee728e6630",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":10},
              "size":{
                "width":200,
                "height":100},
              "limbo":true},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"502304bffb104b539f281ced20e8eb74",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":10,
                    "y":10},
                  "size":{
                    "width":200,
                    "height":100},
                  "limbo":true},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u13.png"}},
{
            "id":"600ef7c96a9347bcb871100b36b0cf0f",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "location":{
                "x":127,
                "y":32},
              "size":{
                "width":144,
                "height":37},
              "limbo":true},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9dbfe63dbdc94bd8910e46f554fc4c00",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":127,
                    "y":32},
                  "size":{
                    "width":144,
                    "height":37},
                  "limbo":true},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"14e845e1c72e4821ace41b96db6ef19f",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":25,
                "y":25},
              "size":{
                "width":300,
                "height":300},
              "limbo":true},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e4bf41b15df04629ade763f9e50337ff",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":25,
                    "y":25},
                  "size":{
                    "width":300,
                    "height":300},
                  "limbo":true},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u19.jpg"}},
{
            "id":"a37335b01b9c4e39b9ddda5921a88092",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":10},
              "size":{
                "width":80,
                "height":80}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7b28f831d3ba40a4b373992dc4ec1da8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":10,
                    "y":10},
                  "size":{
                    "width":80,
                    "height":80}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u19.jpg"}},
{
            "id":"9f98275af8ba4d59ac90fb3f3575c6f2",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"48px",
              "location":{
                "x":120,
                "y":21.5},
              "size":{
                "width":213,
                "height":57}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2c21591a0d704951ba0f1be4b91877c2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"48px",
                  "location":{
                    "x":120,
                    "y":21.5},
                  "size":{
                    "width":213,
                    "height":57}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "5b0694fa5f124324891293724a098df2":{
      "scriptId":"u0",
      "1d0537ac680a48e0803fc441b8a70792":{
        "scriptId":"u1"},
      "59655ed6cfaf48ef851c9d9c5a34957f":{
        "scriptId":"u2"},
      "9398780670274a54b170f02388518565":{
        "scriptId":"u3"},
      "52d88341a3ef4370876955cba99f0d92":{
        "scriptId":"u4"},
      "88f67b4b05a3469a8ee02fe251e1dd36":{
        "scriptId":"u5"},
      "aa35f9c188e94ca5ad65f6b9c81f4f26":{
        "scriptId":"u6"},
      "50dfaf6678b24f6ab138899f4bbd6646":{
        "scriptId":"u7"},
      "40ea58d891644651928d63a76a1eb044":{
        "scriptId":"u8"},
      "2e99d74433a745e98514195fd5ff9e55":{
        "scriptId":"u9"},
      "72767b5952154ff79d927e7536f122d6":{
        "scriptId":"u10"},
      "8c0b0319079844bb816732eb4d19bb70":{
        "scriptId":"u11"},
      "43c245e859b84fddb3d04fb4f8800fcd":{
        "scriptId":"u12"},
      "025ba64a87434580a02052d8fa3f24b5":{
        "scriptId":"u13"},
      "3353de2111b7414999f718eeafb2b732":{
        "scriptId":"u14"},
      "b0d3dd0d92e24655999695ee728e6630":{
        "scriptId":"u15"},
      "502304bffb104b539f281ced20e8eb74":{
        "scriptId":"u16"},
      "600ef7c96a9347bcb871100b36b0cf0f":{
        "scriptId":"u17"},
      "9dbfe63dbdc94bd8910e46f554fc4c00":{
        "scriptId":"u18"},
      "14e845e1c72e4821ace41b96db6ef19f":{
        "scriptId":"u19"},
      "e4bf41b15df04629ade763f9e50337ff":{
        "scriptId":"u20"},
      "a37335b01b9c4e39b9ddda5921a88092":{
        "scriptId":"u21"},
      "7b28f831d3ba40a4b373992dc4ec1da8":{
        "scriptId":"u22"},
      "9f98275af8ba4d59ac90fb3f3575c6f2":{
        "scriptId":"u23"},
      "2c21591a0d704951ba0f1be4b91877c2":{
        "scriptId":"u24"}},
    "b9f3f8db01cc41c3937d658debf8826a":{
      "scriptId":"u25"},
    "fa0590c4566044ad9a32b26cf627a6a6":{
      "scriptId":"u26"},
    "eca95f228c7e49d88531357fde172a1b":{
      "scriptId":"u27"},
    "7a8e434e2cdb4135aeb402b19892510a":{
      "scriptId":"u28"},
    "2ec6a4d4562c4f2f9a088544a1cc8576":{
      "scriptId":"u29"},
    "b89375047bed4b7cb97aa5a42c78e5bf":{
      "scriptId":"u30"},
    "b459c807b1b34fb98ad800819447ad12":{
      "scriptId":"u31"},
    "9fa2af8ef46a4fcc885e6d063179ed6c":{
      "scriptId":"u32"},
    "d725abd2247f465dbf598cde35c26b2c":{
      "scriptId":"u33"},
    "7e6e7b840daa41fdb7827b3a82764b9f":{
      "scriptId":"u34"},
    "e8eee0a4e47a47d988623060b9f709b1":{
      "scriptId":"u35"},
    "aa99630c5a404a9dbe1c34e2a375eda9":{
      "scriptId":"u36"},
    "2e8ea0374dda46889ecad7ce0d8ec4c8":{
      "scriptId":"u37"},
    "db137071e37b46a4b23c791d9953a02e":{
      "scriptId":"u38"},
    "49d0b1d6b6224a88991e6d19c5d8bbf3":{
      "scriptId":"u39"},
    "46ac675f507e4e3db6b57a2f785d17d9":{
      "scriptId":"u40"},
    "4669108ea7654f4c954c5f1662f5ad27":{
      "scriptId":"u41"},
    "12b37dac75ff4679a3e29cc3ab97b2e5":{
      "scriptId":"u42"},
    "2caf079f992048228699aef3b4344598":{
      "scriptId":"u43"},
    "84a796e01c45429ca8c41a00fa5e7df0":{
      "scriptId":"u44"},
    "b0d5e97de0444420898f938bcb63f8a3":{
      "scriptId":"u45"},
    "6df2c976c7514e89995070f7cfedd7bf":{
      "scriptId":"u46"},
    "e98d3ff7e862439cbf5a0fa48961e499":{
      "scriptId":"u47"},
    "3c878be9d1524c51a6412ffd54030d2d":{
      "scriptId":"u48"},
    "eb17fe640fc3439592685928f14fc4df":{
      "scriptId":"u49"},
    "762605ca52744105b4b979b0b2e143bc":{
      "scriptId":"u50"},
    "2f2ed094f9d74b048f72f07d7b9c0176":{
      "scriptId":"u51"},
    "286f50c9844f4312a54e31c962297408":{
      "scriptId":"u52"},
    "0f914af27aec40b8b1d4ca136f666968":{
      "scriptId":"u53"},
    "ed7940385b88436ab99b4b920a04ebbc":{
      "scriptId":"u54"},
    "d79bbc7992324f3fbdc84c290dcefbf3":{
      "scriptId":"u55"},
    "e7b5bcecd6ae440e8dd5b30dd482162c":{
      "scriptId":"u56"},
    "a731598b326e4754904474525494bf5d":{
      "scriptId":"u57"},
    "1d72b63d028c4cb29785ae1b1b5c8488":{
      "scriptId":"u58"},
    "da6b56554d0341e5ac6afcf1f23ec29e":{
      "scriptId":"u59"},
    "f46b6fdcb45e4729bf50ae8c084d2013":{
      "scriptId":"u60"},
    "5532b2435dbf4dc5beb9413223b3c3a8":{
      "scriptId":"u61"},
    "26ae6a92f02c4c5898541732034d99f7":{
      "scriptId":"u62"},
    "33022466b334494bbe496a1f6abc4454":{
      "scriptId":"u63"},
    "e6243989932744e9b52888724a976259":{
      "scriptId":"u64"},
    "8d860daa821042d3b60308b5304a80cc":{
      "scriptId":"u65"},
    "d725e0e8310041b0b07a89db9773793e":{
      "scriptId":"u66"},
    "995af751f1e24acf95fc3fec975af5ad":{
      "scriptId":"u67"},
    "aedbe898a9914a88a71b74f39404a028":{
      "scriptId":"u68"},
    "faac3fca3004411189b14e2c44733fa4":{
      "scriptId":"u69"},
    "b71dc9e1c8d247fea9c1897c350895cd":{
      "scriptId":"u70"},
    "0904024649524f1fb88509f390b96fc2":{
      "scriptId":"u71"},
    "439349667d2942efb01816260ddbb79d":{
      "scriptId":"u72"},
    "5e9df077bc0445d0a614423156aca41b":{
      "scriptId":"u73"},
    "c845e20136b9420fb842933f9e833b62":{
      "scriptId":"u74"},
    "b3faffba4013445c9a42fe5ddb353fd0":{
      "scriptId":"u75"},
    "8038735d15b943788414ed1ed01a1720":{
      "scriptId":"u76"},
    "1db85302cc014a9c9b33915530577a44":{
      "scriptId":"u77"}}});