$axure.loadCurrentPage({
  "url":"inspiration.html",
  "generationDate":new Date(1387305291825),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b3d50d8081e84f2696e87926c8be605b",
    "type":"Axure:Page",
    "name":"inspiration",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"18c7d88456ef47eaaa1f16e919e02330",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"cac9f17c63824a52a0523de90d338bf6"},
{
          "id":"be101d355c384ebf99cabde1ba271466",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6699CC,
              "opacity":1},
            "location":{
              "x":640,
              "y":100},
            "size":{
              "width":320,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"071e17aa93a24505893f031bbfb97edb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6699CC,
                  "opacity":1},
                "location":{
                  "x":640,
                  "y":100},
                "size":{
                  "width":320,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u74.png"}},
{
          "id":"92f51464dcb341b0ac4afc1a6e87c360",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":320,
              "y":100},
            "size":{
              "width":320,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad7c6030b540473fb5f7c753c42b2856",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":320,
                  "y":100},
                "size":{
                  "width":320,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open humor in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"humor.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u76.png"}},
{
          "id":"7cc3f9405cec49fda5e1a6920c243589",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":0,
              "y":160},
            "size":{
              "width":320,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4150f2e23f246248b76ce6e7f401f9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":0,
                  "y":160},
                "size":{
                  "width":320,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open friendship in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"friendship.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u76.png"}},
{
          "id":"8933a7f10a984d1a843ab4ad092807cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":320,
              "y":160},
            "size":{
              "width":320,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbecf69ffa1e47b299afc68154ec6fa0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":320,
                  "y":160},
                "size":{
                  "width":320,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open love in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"love.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u76.png"}},
{
          "id":"7cdee089932649fba2c88f31e9b0f55b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":640,
              "y":160},
            "size":{
              "width":320,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0efbb2d4ac143b3bf904a5d20ddf368",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":640,
                  "y":160},
                "size":{
                  "width":320,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open change in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"change.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u76.png"}},
{
          "id":"695b64077f0f417ba0bbe02d66c1e427",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":0,
              "y":100},
            "size":{
              "width":320,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b622a8199b04ffa84fe6f3cc03b3b62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":0,
                  "y":100},
                "size":{
                  "width":320,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u76.png"}},
{
          "id":"0e6a49d6012d4901b3fed98d92b62380",
          "label":"quoteBox_cat3",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":220},
            "size":{
              "width":960,
              "height":400}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set quoteBox_cat3 to Next fade out 2000ms fade in 2000ms",
                      "panelsToStates":[{
                          "panelPath":["0e6a49d6012d4901b3fed98d92b62380"],
                          "stateInfo":{
                            "setStateType":"next",
                            "stateNumber":0,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "animateOut":{
                                "easing":"fade",
                                "duration":2000},
                              "animateIn":{
                                "easing":"fade",
                                "duration":2000},
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"f2a6ea0845324f608121cb5b05268671",
              "label":"nixon",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"1139b14b47d34317afb2e040af0768d0",
                  "label":"",
                  "parentDynamicPanel":"0e6a49d6012d4901b3fed98d92b62380",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"72px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":65,
                      "y":100},
                    "size":{
                      "width":35,
                      "height":83}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"738c7dd744824c439916ad2352505f33",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0e6a49d6012d4901b3fed98d92b62380",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"72px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":65,
                          "y":100},
                        "size":{
                          "width":35,
                          "height":83}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f92dae6de317465da67148fb4c5594a9",
                  "label":"",
                  "parentDynamicPanel":"0e6a49d6012d4901b3fed98d92b62380",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"72px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":860,
                      "y":100},
                    "size":{
                      "width":35,
                      "height":83}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"aa12868271734f609cf04477a6e28a08",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0e6a49d6012d4901b3fed98d92b62380",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"72px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":860,
                          "y":100},
                        "size":{
                          "width":35,
                          "height":83}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"6461bf8f754244838da9da29fd77a7d2",
                  "label":"",
                  "parentDynamicPanel":"0e6a49d6012d4901b3fed98d92b62380",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"36px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF4F8AAE,
                      "opacity":1},
                    "location":{
                      "x":120,
                      "y":100},
                    "size":{
                      "width":720,
                      "height":84}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"840ca4bd334340cb8c490f011c134921",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0e6a49d6012d4901b3fed98d92b62380",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"36px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF4F8AAE,
                          "opacity":1},
                        "location":{
                          "x":120,
                          "y":100},
                        "size":{
                          "width":720,
                          "height":84}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"77c00043b12b4232ae91c084bd696150",
                  "label":"",
                  "parentDynamicPanel":"0e6a49d6012d4901b3fed98d92b62380",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":120,
                      "y":240},
                    "size":{
                      "width":720,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"43dcb368ebb346a4b6f33b4ebc7028bc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0e6a49d6012d4901b3fed98d92b62380",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":120,
                          "y":240},
                        "size":{
                          "width":720,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"6479a4f41f9d4682bc71aad6ddb8a9c7",
              "label":"franklin",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"a2c6d49410f64db7a8026dd938ed818f",
                  "label":"",
                  "parentDynamicPanel":"0e6a49d6012d4901b3fed98d92b62380",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"72px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":65,
                      "y":100},
                    "size":{
                      "width":35,
                      "height":83}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8d8608230e3d4b588b6a70f95141a852",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0e6a49d6012d4901b3fed98d92b62380",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"72px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":65,
                          "y":100},
                        "size":{
                          "width":35,
                          "height":83}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"723357fdb2134990b63cf1b0ba7f9608",
                  "label":"",
                  "parentDynamicPanel":"0e6a49d6012d4901b3fed98d92b62380",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"72px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":860,
                      "y":100},
                    "size":{
                      "width":35,
                      "height":83}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7f4934b1de77425980dd04eb73a9a1c1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0e6a49d6012d4901b3fed98d92b62380",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"72px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":860,
                          "y":100},
                        "size":{
                          "width":35,
                          "height":83}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ef04f908ea1545f5a8ca58c37d57a516",
                  "label":"",
                  "parentDynamicPanel":"0e6a49d6012d4901b3fed98d92b62380",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"36px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF4F8AAE,
                      "opacity":1},
                    "location":{
                      "x":120,
                      "y":100},
                    "size":{
                      "width":720,
                      "height":84}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"91dde922ef0d4b53b594dab653defbb3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0e6a49d6012d4901b3fed98d92b62380",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"36px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF4F8AAE,
                          "opacity":1},
                        "location":{
                          "x":120,
                          "y":100},
                        "size":{
                          "width":720,
                          "height":84}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a630eb0ce5b643d086423820ad654608",
                  "label":"",
                  "parentDynamicPanel":"0e6a49d6012d4901b3fed98d92b62380",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":120,
                      "y":240},
                    "size":{
                      "width":720,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"767519e5ea5a465988dabb13595937fe",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0e6a49d6012d4901b3fed98d92b62380",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":120,
                          "y":240},
                        "size":{
                          "width":720,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"067baea487eb4405bac312c095363f8f",
              "label":"quote2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"b85f35f05da34610b6df2e3d4655e572",
                  "label":"",
                  "parentDynamicPanel":"0e6a49d6012d4901b3fed98d92b62380",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"72px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":65,
                      "y":100},
                    "size":{
                      "width":35,
                      "height":83}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"392ebf41dea34af78aa4315814254f0b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0e6a49d6012d4901b3fed98d92b62380",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"72px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":65,
                          "y":100},
                        "size":{
                          "width":35,
                          "height":83}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7f7dc9d35f0f4e53a757dce3727de787",
                  "label":"",
                  "parentDynamicPanel":"0e6a49d6012d4901b3fed98d92b62380",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"72px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":860,
                      "y":100},
                    "size":{
                      "width":35,
                      "height":83}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"73e5a76546c04e0aae9bc6f9063434be",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0e6a49d6012d4901b3fed98d92b62380",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"72px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":860,
                          "y":100},
                        "size":{
                          "width":35,
                          "height":83}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8428b231deda42bfb6e2f3d9eb6c0a43",
                  "label":"",
                  "parentDynamicPanel":"0e6a49d6012d4901b3fed98d92b62380",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"36px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF4F8AAE,
                      "opacity":1},
                    "location":{
                      "x":120,
                      "y":100},
                    "size":{
                      "width":720,
                      "height":84}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1b8bc352fb4242b8856c93f33ec75566",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0e6a49d6012d4901b3fed98d92b62380",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"36px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF4F8AAE,
                          "opacity":1},
                        "location":{
                          "x":120,
                          "y":100},
                        "size":{
                          "width":720,
                          "height":84}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b6942c62d66547b181bb531a786858da",
                  "label":"",
                  "parentDynamicPanel":"0e6a49d6012d4901b3fed98d92b62380",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":120,
                      "y":240},
                    "size":{
                      "width":720,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3784adbcbe494e9f9953a6eef2edef9a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0e6a49d6012d4901b3fed98d92b62380",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":120,
                          "y":240},
                        "size":{
                          "width":720,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"eabb7b2c06ad4a71abe35674e152b6ef",
              "label":"quote3",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"ce9683bcf0f44992a3ca8292004b330a",
                  "label":"",
                  "parentDynamicPanel":"0e6a49d6012d4901b3fed98d92b62380",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"72px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":65,
                      "y":100},
                    "size":{
                      "width":35,
                      "height":83}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0bece8314f354e77af425eefe313ef2b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0e6a49d6012d4901b3fed98d92b62380",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"72px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":65,
                          "y":100},
                        "size":{
                          "width":35,
                          "height":83}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f77c01e22312486db682e2a5196856a2",
                  "label":"",
                  "parentDynamicPanel":"0e6a49d6012d4901b3fed98d92b62380",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"72px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":860,
                      "y":100},
                    "size":{
                      "width":35,
                      "height":83}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ef70a29499e0487284da54ace171b33d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0e6a49d6012d4901b3fed98d92b62380",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"72px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":860,
                          "y":100},
                        "size":{
                          "width":35,
                          "height":83}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7839a1ccc22e4870b48fb28e68fcd820",
                  "label":"",
                  "parentDynamicPanel":"0e6a49d6012d4901b3fed98d92b62380",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"36px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF4F8AAE,
                      "opacity":1},
                    "location":{
                      "x":120,
                      "y":100},
                    "size":{
                      "width":720,
                      "height":84}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f18e1f622f35432398b32f635f72b5e4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0e6a49d6012d4901b3fed98d92b62380",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"36px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF4F8AAE,
                          "opacity":1},
                        "location":{
                          "x":120,
                          "y":100},
                        "size":{
                          "width":720,
                          "height":84}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"13f4a08a93a94b57b309806ae16df284",
                  "label":"",
                  "parentDynamicPanel":"0e6a49d6012d4901b3fed98d92b62380",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":120,
                      "y":240},
                    "size":{
                      "width":720,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ebe783838e814efb8dd1802ddc79ea87",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0e6a49d6012d4901b3fed98d92b62380",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":120,
                          "y":240},
                        "size":{
                          "width":720,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"0b1d44cdeaea49368f2fd3838c9452f0",
              "label":"quote4",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"e82da70536d84dd2a8b81b0839f0e79b",
                  "label":"",
                  "parentDynamicPanel":"0e6a49d6012d4901b3fed98d92b62380",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"72px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":65,
                      "y":100},
                    "size":{
                      "width":35,
                      "height":83}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"35f489f7d9c441b586b53c722d268a5c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0e6a49d6012d4901b3fed98d92b62380",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"72px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":65,
                          "y":100},
                        "size":{
                          "width":35,
                          "height":83}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"868a967644224dcfb0fc7601e66d330d",
                  "label":"",
                  "parentDynamicPanel":"0e6a49d6012d4901b3fed98d92b62380",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"72px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":860,
                      "y":100},
                    "size":{
                      "width":35,
                      "height":83}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7d5e0815cc0a4721a5eccfad9c17f3c3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0e6a49d6012d4901b3fed98d92b62380",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"72px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":860,
                          "y":100},
                        "size":{
                          "width":35,
                          "height":83}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"af02628a41104996ad651801fe3ca3cc",
                  "label":"",
                  "parentDynamicPanel":"0e6a49d6012d4901b3fed98d92b62380",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"36px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF4F8AAE,
                      "opacity":1},
                    "location":{
                      "x":120,
                      "y":100},
                    "size":{
                      "width":720,
                      "height":84}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a6ded990fe6e48c0912e6d1138c40750",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0e6a49d6012d4901b3fed98d92b62380",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"36px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF4F8AAE,
                          "opacity":1},
                        "location":{
                          "x":120,
                          "y":100},
                        "size":{
                          "width":720,
                          "height":84}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"28dc30fc140c46218369ddbaf3e69615",
                  "label":"",
                  "parentDynamicPanel":"0e6a49d6012d4901b3fed98d92b62380",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":120,
                      "y":240},
                    "size":{
                      "width":720,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"05ae3e9d13aa4188968045ebb67cc841",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0e6a49d6012d4901b3fed98d92b62380",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":120,
                          "y":240},
                        "size":{
                          "width":720,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]}]}},
  "masters":{
    "cac9f17c63824a52a0523de90d338bf6":{
      "packageId":"cac9f17c63824a52a0523de90d338bf6",
      "type":"Axure:Master",
      "name":"New Master 1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"1d0537ac680a48e0803fc441b8a70792",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":960,
                "height":640}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"59655ed6cfaf48ef851c9d9c5a34957f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":960,
                    "height":640}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u1.png"}},
{
            "id":"9398780670274a54b170f02388518565",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":960,
                "height":100}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"52d88341a3ef4370876955cba99f0d92",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":960,
                    "height":100}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u3.png"}},
{
            "id":"88f67b4b05a3469a8ee02fe251e1dd36",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":100,
                "height":100}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"aa35f9c188e94ca5ad65f6b9c81f4f26",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":100,
                    "height":100}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u5.png"}},
{
            "id":"50dfaf6678b24f6ab138899f4bbd6646",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "location":{
                "x":167,
                "y":293},
              "size":{
                "width":16,
                "height":37},
              "limbo":true},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"40ea58d891644651928d63a76a1eb044",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":167,
                    "y":293},
                  "size":{
                    "width":16,
                    "height":37},
                  "limbo":true},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"2e99d74433a745e98514195fd5ff9e55",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "location":{
                "x":177,
                "y":303},
              "size":{
                "width":16,
                "height":37},
              "limbo":true},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"72767b5952154ff79d927e7536f122d6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":177,
                    "y":303},
                  "size":{
                    "width":16,
                    "height":37},
                  "limbo":true},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"8c0b0319079844bb816732eb4d19bb70",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "location":{
                "x":294,
                "y":322},
              "size":{
                "width":137,
                "height":28},
              "limbo":true},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"43c245e859b84fddb3d04fb4f8800fcd",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":294,
                    "y":322},
                  "size":{
                    "width":137,
                    "height":28},
                  "limbo":true},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"025ba64a87434580a02052d8fa3f24b5",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":10},
              "size":{
                "width":200,
                "height":100},
              "limbo":true},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3353de2111b7414999f718eeafb2b732",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":10,
                    "y":10},
                  "size":{
                    "width":200,
                    "height":100},
                  "limbo":true},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u13.png"}},
{
            "id":"b0d3dd0d92e24655999695ee728e6630",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":10},
              "size":{
                "width":200,
                "height":100},
              "limbo":true},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"502304bffb104b539f281ced20e8eb74",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":10,
                    "y":10},
                  "size":{
                    "width":200,
                    "height":100},
                  "limbo":true},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u13.png"}},
{
            "id":"600ef7c96a9347bcb871100b36b0cf0f",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "location":{
                "x":127,
                "y":32},
              "size":{
                "width":144,
                "height":37},
              "limbo":true},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9dbfe63dbdc94bd8910e46f554fc4c00",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":127,
                    "y":32},
                  "size":{
                    "width":144,
                    "height":37},
                  "limbo":true},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"14e845e1c72e4821ace41b96db6ef19f",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":25,
                "y":25},
              "size":{
                "width":300,
                "height":300},
              "limbo":true},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e4bf41b15df04629ade763f9e50337ff",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":25,
                    "y":25},
                  "size":{
                    "width":300,
                    "height":300},
                  "limbo":true},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u19.jpg"}},
{
            "id":"a37335b01b9c4e39b9ddda5921a88092",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":10},
              "size":{
                "width":80,
                "height":80}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7b28f831d3ba40a4b373992dc4ec1da8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":10,
                    "y":10},
                  "size":{
                    "width":80,
                    "height":80}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u19.jpg"}},
{
            "id":"9f98275af8ba4d59ac90fb3f3575c6f2",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"48px",
              "location":{
                "x":120,
                "y":21.5},
              "size":{
                "width":213,
                "height":57}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2c21591a0d704951ba0f1be4b91877c2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"48px",
                  "location":{
                    "x":120,
                    "y":21.5},
                  "size":{
                    "width":213,
                    "height":57}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "18c7d88456ef47eaaa1f16e919e02330":{
      "scriptId":"u0",
      "1d0537ac680a48e0803fc441b8a70792":{
        "scriptId":"u1"},
      "59655ed6cfaf48ef851c9d9c5a34957f":{
        "scriptId":"u2"},
      "9398780670274a54b170f02388518565":{
        "scriptId":"u3"},
      "52d88341a3ef4370876955cba99f0d92":{
        "scriptId":"u4"},
      "88f67b4b05a3469a8ee02fe251e1dd36":{
        "scriptId":"u5"},
      "aa35f9c188e94ca5ad65f6b9c81f4f26":{
        "scriptId":"u6"},
      "50dfaf6678b24f6ab138899f4bbd6646":{
        "scriptId":"u7"},
      "40ea58d891644651928d63a76a1eb044":{
        "scriptId":"u8"},
      "2e99d74433a745e98514195fd5ff9e55":{
        "scriptId":"u9"},
      "72767b5952154ff79d927e7536f122d6":{
        "scriptId":"u10"},
      "8c0b0319079844bb816732eb4d19bb70":{
        "scriptId":"u11"},
      "43c245e859b84fddb3d04fb4f8800fcd":{
        "scriptId":"u12"},
      "025ba64a87434580a02052d8fa3f24b5":{
        "scriptId":"u13"},
      "3353de2111b7414999f718eeafb2b732":{
        "scriptId":"u14"},
      "b0d3dd0d92e24655999695ee728e6630":{
        "scriptId":"u15"},
      "502304bffb104b539f281ced20e8eb74":{
        "scriptId":"u16"},
      "600ef7c96a9347bcb871100b36b0cf0f":{
        "scriptId":"u17"},
      "9dbfe63dbdc94bd8910e46f554fc4c00":{
        "scriptId":"u18"},
      "14e845e1c72e4821ace41b96db6ef19f":{
        "scriptId":"u19"},
      "e4bf41b15df04629ade763f9e50337ff":{
        "scriptId":"u20"},
      "a37335b01b9c4e39b9ddda5921a88092":{
        "scriptId":"u21"},
      "7b28f831d3ba40a4b373992dc4ec1da8":{
        "scriptId":"u22"},
      "9f98275af8ba4d59ac90fb3f3575c6f2":{
        "scriptId":"u23"},
      "2c21591a0d704951ba0f1be4b91877c2":{
        "scriptId":"u24"}},
    "be101d355c384ebf99cabde1ba271466":{
      "scriptId":"u25"},
    "071e17aa93a24505893f031bbfb97edb":{
      "scriptId":"u26"},
    "92f51464dcb341b0ac4afc1a6e87c360":{
      "scriptId":"u27"},
    "ad7c6030b540473fb5f7c753c42b2856":{
      "scriptId":"u28"},
    "7cc3f9405cec49fda5e1a6920c243589":{
      "scriptId":"u29"},
    "f4150f2e23f246248b76ce6e7f401f9c":{
      "scriptId":"u30"},
    "8933a7f10a984d1a843ab4ad092807cf":{
      "scriptId":"u31"},
    "fbecf69ffa1e47b299afc68154ec6fa0":{
      "scriptId":"u32"},
    "7cdee089932649fba2c88f31e9b0f55b":{
      "scriptId":"u33"},
    "a0efbb2d4ac143b3bf904a5d20ddf368":{
      "scriptId":"u34"},
    "695b64077f0f417ba0bbe02d66c1e427":{
      "scriptId":"u35"},
    "5b622a8199b04ffa84fe6f3cc03b3b62":{
      "scriptId":"u36"},
    "0e6a49d6012d4901b3fed98d92b62380":{
      "scriptId":"u37"},
    "1139b14b47d34317afb2e040af0768d0":{
      "scriptId":"u38"},
    "738c7dd744824c439916ad2352505f33":{
      "scriptId":"u39"},
    "f92dae6de317465da67148fb4c5594a9":{
      "scriptId":"u40"},
    "aa12868271734f609cf04477a6e28a08":{
      "scriptId":"u41"},
    "6461bf8f754244838da9da29fd77a7d2":{
      "scriptId":"u42"},
    "840ca4bd334340cb8c490f011c134921":{
      "scriptId":"u43"},
    "77c00043b12b4232ae91c084bd696150":{
      "scriptId":"u44"},
    "43dcb368ebb346a4b6f33b4ebc7028bc":{
      "scriptId":"u45"},
    "a2c6d49410f64db7a8026dd938ed818f":{
      "scriptId":"u46"},
    "8d8608230e3d4b588b6a70f95141a852":{
      "scriptId":"u47"},
    "723357fdb2134990b63cf1b0ba7f9608":{
      "scriptId":"u48"},
    "7f4934b1de77425980dd04eb73a9a1c1":{
      "scriptId":"u49"},
    "ef04f908ea1545f5a8ca58c37d57a516":{
      "scriptId":"u50"},
    "91dde922ef0d4b53b594dab653defbb3":{
      "scriptId":"u51"},
    "a630eb0ce5b643d086423820ad654608":{
      "scriptId":"u52"},
    "767519e5ea5a465988dabb13595937fe":{
      "scriptId":"u53"},
    "b85f35f05da34610b6df2e3d4655e572":{
      "scriptId":"u54"},
    "392ebf41dea34af78aa4315814254f0b":{
      "scriptId":"u55"},
    "7f7dc9d35f0f4e53a757dce3727de787":{
      "scriptId":"u56"},
    "73e5a76546c04e0aae9bc6f9063434be":{
      "scriptId":"u57"},
    "8428b231deda42bfb6e2f3d9eb6c0a43":{
      "scriptId":"u58"},
    "1b8bc352fb4242b8856c93f33ec75566":{
      "scriptId":"u59"},
    "b6942c62d66547b181bb531a786858da":{
      "scriptId":"u60"},
    "3784adbcbe494e9f9953a6eef2edef9a":{
      "scriptId":"u61"},
    "ce9683bcf0f44992a3ca8292004b330a":{
      "scriptId":"u62"},
    "0bece8314f354e77af425eefe313ef2b":{
      "scriptId":"u63"},
    "f77c01e22312486db682e2a5196856a2":{
      "scriptId":"u64"},
    "ef70a29499e0487284da54ace171b33d":{
      "scriptId":"u65"},
    "7839a1ccc22e4870b48fb28e68fcd820":{
      "scriptId":"u66"},
    "f18e1f622f35432398b32f635f72b5e4":{
      "scriptId":"u67"},
    "13f4a08a93a94b57b309806ae16df284":{
      "scriptId":"u68"},
    "ebe783838e814efb8dd1802ddc79ea87":{
      "scriptId":"u69"},
    "e82da70536d84dd2a8b81b0839f0e79b":{
      "scriptId":"u70"},
    "35f489f7d9c441b586b53c722d268a5c":{
      "scriptId":"u71"},
    "868a967644224dcfb0fc7601e66d330d":{
      "scriptId":"u72"},
    "7d5e0815cc0a4721a5eccfad9c17f3c3":{
      "scriptId":"u73"},
    "af02628a41104996ad651801fe3ca3cc":{
      "scriptId":"u74"},
    "a6ded990fe6e48c0912e6d1138c40750":{
      "scriptId":"u75"},
    "28dc30fc140c46218369ddbaf3e69615":{
      "scriptId":"u76"},
    "05ae3e9d13aa4188968045ebb67cc841":{
      "scriptId":"u77"}}});